server:
  port : 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inhabitant
    username: main
    password: main
  flyway:
    enabled: true
    validate-on-migrate: true

#logging:
#  level:
#    root: DEBUG